source 'https://github.com/CocoaPods/Specs.git'
xcodeproj 'Goodrich/Goodrich.xcodeproj'
platform :ios, '8.0'
pod 'AFNetworking', '2.5.0'
pod 'Toast', '~> 2.2'
pod 'SSKeychain'
pod 'JTSImageViewController'
pod 'SDWebImage', '~>3.6'
pod 'ViSearch', '~>0.0.4'
pod 'NewRelicAgent'
